[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('read', 'add', 'search', 'sync', 'status')]
    [string]$Command = 'read',
    [string]$Text = '',
    [string]$Query = '',
    [string]$Project = '',
    [string]$Agent = '',
    [switch]$Hot
)

$ErrorActionPreference = 'Stop'
$Root     = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$MemFile  = Join-Path $Root 'MEMORY.md'
$LogDir   = Join-Path $Root 'log'
$ProjDir  = Join-Path $Root 'projects'
$HostsFile = Join-Path $Root 'hosts.json'
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

if (-not $Agent) { $Agent = if ($env:AI_AGENT) { $env:AI_AGENT } else { 'agent' } }
if (-not (Test-Path $LogDir))  { New-Item -ItemType Directory -Force -Path $LogDir  | Out-Null }
if (-not (Test-Path $ProjDir)) { New-Item -ItemType Directory -Force -Path $ProjDir | Out-Null }

function Read-Text([string]$Path) {
    if (Test-Path $Path) { return [System.IO.File]::ReadAllText($Path) }
    return ''
}

function Append-Text([string]$Path, [string]$Content) {
    [System.IO.File]::WriteAllText($Path, (Read-Text $Path) + $Content, $Utf8NoBom)
}

function Append-HotLog([string]$Line) {
    $content = Read-Text $MemFile
    if ($content -notmatch '(?m)^## Hot log \(auto\)') {
        $content = $content.TrimEnd() + "`r`n`r`n## Hot log (auto)`r`n"
        [System.IO.File]::WriteAllText($MemFile, $content, $Utf8NoBom)
    }
    Append-Text $MemFile ($Line + "`r`n")
}

function Get-BlockTargets {
    if (Test-Path $HostsFile) {
        try {
            $cfg = Get-Content $HostsFile -Raw | ConvertFrom-Json
            if ($cfg.block_targets) { return @($cfg.block_targets) }
        } catch { }
    }
    return @(
        (Join-Path $env:USERPROFILE '.codex\AGENTS.md'),
        (Join-Path $env:USERPROFILE '.zcode\workspace\default\AGENTS.md')
    )
}

$Begin = '<!-- AI-MEMORY:BEGIN -->'
$End   = '<!-- AI-MEMORY:END -->'

function Update-ManagedBlock([string]$Path, [string]$Body) {
    $block = "$Begin`r`n" + $Body.TrimEnd() + "`r`n$End"
    $dir = Split-Path -Parent $Path
    if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $content = Read-Text $Path
    if ($content -match [regex]::Escape($Begin)) {
        $pattern = "(?s)" + [regex]::Escape($Begin) + ".*?" + [regex]::Escape($End)
        $content = [regex]::Replace($content, $pattern, [System.Text.RegularExpressions.MatchEvaluator] { param($m) $block })
    } else {
        if ($content.Trim().Length -gt 0) { $content = $content.TrimEnd() + "`r`n`r`n" }
        $content = $content + $block + "`r`n"
    }
    [System.IO.File]::WriteAllText($Path, $content, $Utf8NoBom)
}

switch ($Command) {

    'read' {
        Write-Output (Read-Text $MemFile)
    }

    'add' {
        if (-not $Text) { throw 'add requires -Text "..."' }
        $now = Get-Date
        $stamp = $now.ToString('yyyy-MM-dd HH:mm')
        $line = "- $stamp [$Agent] $Text"
        if ($Project) {
            $p = Join-Path $ProjDir ($Project + '.md')
            if (-not (Test-Path $p)) { [System.IO.File]::WriteAllText($p, "# Project memory: $Project`r`n", $Utf8NoBom) }
            Append-Text $p ($line + "`r`n")
            Write-Output "saved -> projects\$Project.md"
        } else {
            $p = Join-Path $LogDir ($now.ToString('yyyy-MM') + '.md')
            if (-not (Test-Path $p)) { [System.IO.File]::WriteAllText($p, "# Memory log $($now.ToString('yyyy-MM'))`r`n", $Utf8NoBom) }
            Append-Text $p ($line + "`r`n")
            Write-Output "saved -> log\$($now.ToString('yyyy-MM')).md"
        }
        if ($Hot) {
            Append-HotLog $line
            Write-Output 'also appended to MEMORY.md -> Hot log (auto)'
        }
    }

    'search' {
        if (-not $Query) { throw 'search requires -Query "..."' }
        $files = @()
        if (Test-Path $MemFile) { $files += $MemFile }
        $files += Get-ChildItem $LogDir -Filter *.md -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName
        $files += Get-ChildItem $ProjDir -Filter *.md -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName
        if (-not $files) { Write-Output 'memory is empty'; break }
        $hits = Select-String -Path $files -Pattern $Query -SimpleMatch -ErrorAction SilentlyContinue
        if (-not $hits) { Write-Output "no matches for: $Query"; break }
        foreach ($h in $hits) {
            $rel = $h.Path.Replace($Root + '\', '')
            Write-Output ("{0}:{1}: {2}" -f $rel, $h.LineNumber, $h.Line.Trim())
        }
    }

    'sync' {
        $memory = Read-Text $MemFile
        $body = @"
## Shared agent memory (auto-synced)

This block is generated by mem.ps1 sync. Edit MEMORY.md, then re-run sync.
Full store: $Root (log\ + projects\; search via tools\mem.ps1 search -Query "...").
Save durable facts: powershell -NoProfile -File "$Root\tools\mem.ps1" add -Text "..." -Agent codex [-Hot] [-Project name].
Never store secrets here.

--- BEGIN SHARED MEMORY CONTENT ---

$memory

--- END SHARED MEMORY CONTENT ---
"@
        foreach ($target in (Get-BlockTargets)) {
            Update-ManagedBlock $target $body
            Write-Output "synced -> $target"
        }
    }

    'status' {
        $mem = Get-Item $MemFile -ErrorAction SilentlyContinue
        Write-Output "root        : $Root"
        if ($mem) { Write-Output ("MEMORY.md   : {0} bytes, {1} lines" -f $mem.Length, (Get-Content $MemFile -ErrorAction SilentlyContinue).Count) }
        else { Write-Output "MEMORY.md   : missing" }
        $logCount = (Get-ChildItem $LogDir -Filter *.md -ErrorAction SilentlyContinue | Measure-Object).Count
        $projCount = (Get-ChildItem $ProjDir -Filter *.md -ErrorAction SilentlyContinue | Measure-Object).Count
        Write-Output "log files   : $logCount   project files: $projCount"
        foreach ($p in (Get-BlockTargets)) {
            if (Test-Path $p) { Write-Output ("block       : {0}  (updated {1})" -f $p, (Get-Item $p).LastWriteTime) }
            else { Write-Output "block       : $p  (missing - run sync)" }
        }
    }
}
